Start project
nonenane/java-explore-with-me pull request #1
Opened 2022-11-14 15:29 UTC by nonenane

2022-11-22 20:55 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/pom.xml
> +    <artifactId>ExploreWithMeApp</artifactId>
Сразу бросились в глаза большие буквы... в Java так не принято!

Вот отсылочка на `naming conventions`
https://maven.apache.org/guides/mini/guide-naming-conventions.html

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/ExploreWithMeApp.java
> +public class ExploreWithMeApp {
Мой любимый класс! Он всегда идеален! )))

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/controllers/ErrorHandler.java
> +        e.printStackTrace();
Вместо отдельного e.printStackTrace();
Можно добавить в логер третий параметр, посмотри сигнатуру методов...

`log.info("error: ForbiddenException", e.getMessage(), e);`

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/controllers/ErrorHandler.java
> +        log.info("error: Exception");
Почему логируем на уровне `info`, если мы тут - то это warn/error

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/controllers/admin/UserAdminController.java
> +    //@ResponseStatus(HttpStatus.CREATED)
Не забывай удалять ошметки...

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/controllers/priv/EventPrivateController.java
> +    /*
Оформляй это уже в стиле JavaDoc

```
    /**
     * Добавление нового события
     */
```

Это сделает этот текст видимым при `ctrl+Q`
![image](https://user-images.githubusercontent.com/3994663/203409757-5c18baa5-197f-43b3-aa2e-e12c851a0634.png)

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/controllers/priv/EventPrivateController.java
> +        authenticationService.checkUserId(userId);
метод описан как `boolean checkUserId(Long userId)`, но я не увидел чтобы возвращаемым значением пользовались...
Получается что только вылет ексепшена имеет смысл.
И тогда можно более честно назвать метод: `throwIfUserNotFound`

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/controllers/priv/ParticipationRequestPrivateController.java
> +    public ParticipationRequestPrivateController(AuthenticationService authenticationService, ParticipationRequestService requestService) {
Не влезло в 120 символов, делай перенос...

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/controllers/priv/SubscriptionPrivateController.java
> +    public List<EventShortDto> getSubscriptionEvents(@PathVariable Long userId,
Перенос

```
    public List<EventShortDto> getSubscriptionEvents(
            @PathVariable Long userId,
            @RequestParam(required = false) EventsSortType sort,
            @RequestParam(required = false, defaultValue = "0") @PositiveOrZero Integer from,
            @RequestParam(required = false, defaultValue = "10") @Positive Integer size) {
        authenticationService.checkUserId(userId);
    .......
```

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/controllers/priv/SubscriptionPrivateController.java
> +        List<EventShortDto> eventList = subscriptionService.getSubscriptionEvents(userId, sort, from, size);
`eventList` не добавляем в название тип коллекции!
Просто `events` or `subscriptionEvents` or `subEvents`

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/controllers/publ/CompilationPublicController.java
> +        List<CompilationDto> dtoList = compilationService.getCompilations(pinned, from, size);
Я обязательно проверю названия всех переменных!!!

Прозвучало как угроза?! ))))

Шучу... но ты, конечно же постарайся! ))

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/mappers/CategoriesMapper.java
> +            return null;
В `Java` не принято экономить на скобочках!

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/services/CategoryService.java
> +    List<CategoryDto> getCategories(Integer from, Integer size);
Методы не висят в воздухе!
Поэтому нет нужды в них повторять название сущности, например: `categoryService.getCategories`

Получается масло-масляное! 

Лучше: `categoryService.get` `categoryService.getAll`

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/services/CategoryService.java
> +    CategoryDto patchCategory(CategoryDto categoryDto);
И упрощение названий поможет тебе придти к универсальным интерфейсам. `T`
Возможно длинные названия просто мешают тебе заметить похожесть некоторых методов в интерфейсах...

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/services/authentication/AuthenticationServiceImpl.java
> +        userRepository.findById(userId)
Есть настройка выравнивающая вот так:

```
        userRepository.findById(userId)
                      .orElseThrow(() -> new NotFoundException("User with id=" + userId + " was not found."));
```

Выглядит лучше, правда? )

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/models/User.java
> +    private String name;
У полей не все свойства которыми они наделены в БД...
Например name в базе NOT NULL, а 
email NOT NULL и длинной 512

И за этим стоит проследить везде...

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/services/impl/CategoryServiceImpl.java
> +        List<Category> categoryList = categoryRepository.searchCategoriesPage(from, size);
Можно проще:

```
    @Override
    public List<CategoryDto> getCategories(Integer from, Integer size) {
        return categoryRepository.searchCategoriesPage(from, size).stream()
                                 .map(CategoriesMapper::toCategoryDto)
                                 .collect(Collectors.toList());
    }
```

И, что важно! переноси каждую осмысленную операцию в цепочке на новую строку!

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/services/impl/CategoryServiceImpl.java
> +        return CategoriesMapper.toCategoryDto(category);
Статический метод может быть заимпорчен предварительно, и код будет выглядеть проще:

`return toCategoryDto(category)`

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/services/impl/CategoryServiceImpl.java
> +            throw new ForbiddenException("Find event with this category");
Давай больше информации в логи и в ответные сообщения клиенту.
У тебя же есть `catId` - вот и укажи что именно по нему не найдено!

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/services/impl/CompilationServiceImpl.java
> +            throw new NotFoundException("Compilation already contain this event");
Может ты перепутал ексепшн?
Cудя по тексту мы должны дать `HTTP` код `409 Conflict`, а эксепшн у тебя NotFound это `404` код.

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/services/impl/EventServiceImpl.java
> +        if (updateEventRequest.getTitle() != null)
Не экономим на `{}`

2022-11-22 20:55 UTC, FanaticFiz commented on StatApp/src/main/resources/application.properties
> +server.port=9090
А я обычно топлю за то чтобы вы сразу привыкали к написанию файла свойств для приложения в формате `yaml -> application.yml`

Если есть силы можешь попробовать, должно понравится! ))

2022-11-22 20:55 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/resources/schema.sql
> +drop table if exists users, subscriptions, categories, events, compilations, events_compilation, participation_requests;
В схеме SQL не хватает выравнивания и неплохо было бы писать SQL команды в верхнем регистре: `CREATE TABLE`

2022-11-23 13:11 UTC, nonenane commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/mappers/CategoriesMapper.java
> +            return null;
Это всё ардуина, там чем меньше символов, тем меньше объема сожрёт код:)

2022-11-23 13:18 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/mappers/CategoriesMapper.java
> +            return null;
О_о "ардуина" ну так то я не против оставляй как есть (у тебя много где это по проекту)
но вообще конечно так не принято )

2022-11-23 13:19 UTC, nonenane commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/services/CategoryService.java
> +    CategoryDto patchCategory(CategoryDto categoryDto);
Надо подумать над этим будет в будущем :)

2022-11-23 13:24 UTC, nonenane commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/services/authentication/AuthenticationServiceImpl.java
> +        userRepository.findById(userId)
где-то выставляется она? а то ctrl+alt+l не работает:)

2022-11-23 13:28 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/services/authentication/AuthenticationServiceImpl.java
> +        userRepository.findById(userId)
да, чтобы это заработало по хотКеям надо преднастроить, но я точно не помню какая из галочек! ))

![image](https://user-images.githubusercontent.com/3994663/203558537-68ea2f08-9347-4d43-b3cb-fc8c69d9a1ee.png)

2022-11-23 13:28 UTC, FanaticFiz commented on ExploreWithMeApp/src/main/java/ru/practicum/explorewithme/services/authentication/AuthenticationServiceImpl.java
> +        userRepository.findById(userId)
небольшой тебе квест! ))

2022-11-24 19:47 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-24 19:47 UTC, FanaticFiz commented on explorewithmeapp/src/main/java/ru/practicum/explorewithme/controllers/admin/CategoryAdminController.java
> +        log.info("Выполнен запрос patchCategory");
Отличный пример копи-пасты! )))

2022-11-24 19:47 UTC, FanaticFiz commented on explorewithmeapp/src/main/java/ru/practicum/explorewithme/controllers/admin/CategoryAdminController.java
> +        log.info("Выполнен запрос createCategory");
Наполняй лог полезной информацией:

`log.info("Запрос на создание категории: {}", categoryDto);`

2022-11-24 19:47 UTC, FanaticFiz commented on explorewithmeapp/src/main/java/ru/practicum/explorewithme/models/Category.java
> +    @Column(unique = true, length = 64)
Не провёл достаточно работы по "синхронизации" описания полей в коде с реальностью в БД.

Не хватает: `nullable = false`

2022-11-24 19:47 UTC, FanaticFiz commented on explorewithmeapp/src/main/java/ru/practicum/explorewithme/models/Compilation.java
> +    private String title;
Есть вообще не описанные поля ((

Я, по прежнему не буду комментировать прям все места.
Но ты обязан провести эту работу.

2022-11-24 19:47 UTC, FanaticFiz commented on explorewithmeapp/src/main/java/ru/practicum/explorewithme/services/impl/CategoryServiceImpl.java
> +            throw new ConflictException("Add user");
Клиент получив такой ответ явно будет не доволен, совершенно не раскрыто в сообщение что произошло...

2022-11-24 19:47 UTC, FanaticFiz commented on explorewithmeapp/src/main/java/ru/practicum/explorewithme/services/impl/CompilationServiceImpl.java
> +            compilationRepository.deleteEventFromCompilation(compId, eventId);
Смотри, тебе не нужно удалять сущность вручную... это сделает хибер.
Всё что нужно тебе сделать так это удалить сущность из коллекции...

```
        Compilation compilation = repository.findById(compId)
                                            .orElseThrow(() -> new NotFoundException("Compilation", compId));
        compilation.getEvents().removeIf(event -> event.getId().equals(eventId));

        repository.save(compilation);
```

Ну и не очень мне заходит твой метод `getCompilationFromDB` по-моему ничего не сэкономили, и мне всё время приходится в голове держать что в том методе происходит вместо того чтобы сразу увидеть две строчки кода...

2022-11-24 19:47 UTC, FanaticFiz commented on explorewithmeapp/src/main/java/ru/practicum/explorewithme/services/impl/CompilationServiceImpl.java
> +            compilationRepository.addEventToCompilation(compId, eventId);
С добавлением та же история... не нужно самостоятельно создавать в БД. 
Хибер сделает связь при добавлении в коллекцию.

Обрати на это внимание!

2022-11-24 19:47 UTC, FanaticFiz commented on explorewithmeapp/src/main/java/ru/practicum/explorewithme/services/impl/EventServiceImpl.java
> +        if (updateEventRequest.getTitle() != null) {
Большой кусок дублирующегося кода
строки 167-175 и 136-144...

нужно вынести в метод.

2022-11-24 19:47 UTC, FanaticFiz commented on explorewithmeapp/src/main/java/ru/practicum/explorewithme/services/impl/EventServiceImpl.java
> +            throw new ForbiddenException("Event is not PENDING");
В этом классе ты часто используешь `ForbiddenException` и всегда не по делу!
Да и не можешь ты его использовать по делу, поскольку этот эксепшн подразумевает  запрет на доступ по правам, которых в этой работе нет...

Валидно будет использовать `IllegalStateException`

2022-11-24 19:47 UTC, FanaticFiz commented on explorewithmeapp/src/main/java/ru/practicum/explorewithme/services/impl/EventServiceImpl.java
> +        if (event.getState() == EventState.PUBLISHED) {
Используй статик переменные так

`if (event.getState() == PUBLISHED) {` - короче и читабельнее...

2022-11-24 19:47 UTC, FanaticFiz commented on explorewithmeapp/src/main/java/ru/practicum/explorewithme/services/impl/UserServiceImpl.java
> +            User user = new User(null, newUserRequest.getName(), newUserRequest.getEmail(), new HashSet<>());
А где же `userMapper` ???

2022-11-24 19:47 UTC, FanaticFiz commented on statclientanddtolibrary/src/main/java/ru/practicum/explorewithme/exceptions/ForbiddenException.java
> +public class ForbiddenException extends RuntimeException {
В нашей работе не может быть этого ексепшена и мы не можем возвращать 403 код...

2022-11-30 08:54 UTC, nonenane commented on statclientanddtolibrary/src/main/java/ru/practicum/explorewithme/exceptions/ForbiddenException.java
> +public class ForbiddenException extends RuntimeException {
Так по API было, вопрос не ко мне а к авторам задачи.

2022-11-30 08:55 UTC, nonenane commented on explorewithmeapp/src/main/java/ru/practicum/explorewithme/services/impl/EventServiceImpl.java
> +            throw new ForbiddenException("Event is not PENDING");
Так по API было, вопрос не ко мне а к авторам задачи.

2022-11-30 08:57 UTC, nonenane commented on explorewithmeapp/src/main/java/ru/practicum/explorewithme/services/impl/EventServiceImpl.java
> +        if (event.getState() == EventState.PUBLISHED) {
Возможно, но если PUBLISHED уникальный и ссылается на  EventState, а если будет ещё какой нибудь ENUM и мы его будем использовать в этом сервисе и он будет содержать PUBLISHED, тогда надо будет менять..

2022-11-30 09:08 UTC, nonenane commented on explorewithmeapp/src/main/java/ru/practicum/explorewithme/services/impl/EventServiceImpl.java
> +        if (updateEventRequest.getTitle() != null) {
сложность в том что в patch(UpdateEventRequest updateEventRequest)
а в adminUpdateEvent(AdminUpdateEventRequest updateEventRequest, Long eventId)
Чуть чуть разные DTO приходят изза этого затрудняюсь вынести их.

2022-12-01 17:13 UTC, FanaticFiz approved these changes

2022-12-04 08:23 UTC, merged